import React from 'react';
import * as Icons from 'lucide-react';

interface LucideIconProps {
  name: string;
  className?: string;
  size?: number;
}

const iconMap: Record<string, React.ComponentType<{ className?: string; size?: number }>> = {
  utensils: Icons.Utensils,
  home: Icons.Home,
  car: Icons.Car,
  smile: Icons.Smile,
  heartpulse: Icons.HeartPulse,
  shoppingbag: Icons.ShoppingBag,
  sparkles: Icons.Sparkles,
  bookopen: Icons.BookOpen,
  gift: Icons.Gift,
  laptop: Icons.Laptop,
  plane: Icons.Plane,
  piggybank: Icons.PiggyBank,
  wallet: Icons.Wallet,
  dollarsign: Icons.DollarSign,
  plus: Icons.Plus,
  minus: Icons.Minus,
  trendingup: Icons.TrendingUp,
  trendingdown: Icons.TrendingDown,
  settings: Icons.Settings,
  calendar: Icons.Calendar,
  chevronright: Icons.ChevronRight,
  chevronleft: Icons.ChevronLeft,
  chevrondown: Icons.ChevronDown,
  trash2: Icons.Trash2,
  edit3: Icons.Edit3,
  pencil: Icons.Pencil,
  morevertical: Icons.MoreVertical,
  checkcircle: Icons.CheckCircle,
  alertcircle: Icons.AlertCircle,
  rotateccw: Icons.RotateCcw,
  filetext: Icons.FileText,
  piechart: Icons.PieChart,
  info: Icons.Info,
  search: Icons.Search,
  arrowright: Icons.ArrowRight,
  arrowleft: Icons.ArrowLeft,
  x: Icons.X,
  coins: Icons.Coins,
  calculator: Icons.Calculator,
  user: Icons.User,
  arrowdownright: Icons.ArrowDownRight,
  arrowupright: Icons.ArrowUpRight,
  history: Icons.History,
  check: Icons.Check,
  tv: Icons.Tv,
  shirt: Icons.Shirt,
  gamepad2: Icons.Gamepad2,
  heart: Icons.Heart,
  wrench: Icons.Wrench,
  coffee: Icons.Coffee,
  dumbbell: Icons.Dumbbell,
  shield: Icons.Shield,
  graduationcap: Icons.GraduationCap,
  baby: Icons.Baby,
  pawprint: Icons.PawPrint,
  lightbulb: Icons.Lightbulb,
  phone: Icons.Phone,
  creditcard: Icons.CreditCard,
  receipt: Icons.Receipt,
  key: Icons.Key,
  banknote: Icons.Banknote,
  landmark: Icons.Landmark,
  percent: Icons.Percent,
  briefcase: Icons.Briefcase,
  scale: Icons.Scale,
  shoppingbasket: Icons.ShoppingBasket,
  hammer: Icons.Hammer,
  plug: Icons.Plug,
  scissors: Icons.Scissors,
  store: Icons.Store,
  package: Icons.Package,
  soup: Icons.Soup,
  truck: Icons.Truck,
  flame: Icons.Flame,
  sofa: Icons.Sofa,
  bath: Icons.Bath,
  music: Icons.Music,
  film: Icons.Film,
  camera: Icons.Camera,
  palette: Icons.Palette,
  beer: Icons.Beer,
  wine: Icons.Wine,
  dices: Icons.Dices,
  trophy: Icons.Trophy,
  clapperboard: Icons.Clapperboard,
  theater: Icons.Theater,
  brush: Icons.Brush,
  crown: Icons.Crown,
  partypopper: Icons.PartyPopper,
  guitar: Icons.Guitar,
  compass: Icons.Compass,
  globe: Icons.Globe,
  map: Icons.Map,
  luggage: Icons.Luggage,
  bike: Icons.Bike,
  train: Icons.Train,
  hotel: Icons.Hotel,
  caravan: Icons.Caravan,
  ship: Icons.Ship,
  footprints: Icons.Footprints,
  mappin: Icons.MapPin,
  ticket: Icons.Ticket,
  tent: Icons.Tent,
  anchor: Icons.Anchor,
  fuel: Icons.Fuel,
  apple: Icons.Apple,
  pill: Icons.Pill,
  stethoscope: Icons.Stethoscope,
  trees: Icons.Trees,
  flower2: Icons.Flower2,
  users: Icons.Users,
  hearthandshake: Icons.HeartHandshake,
  brain: Icons.Brain,
  salad: Icons.Salad,
  crosshair: Icons.Crosshair,
  syringe: Icons.Syringe,
  bed: Icons.Bed,
  alertoctagon: Icons.AlertOctagon,
  lock: Icons.Lock,
  unlock: Icons.Unlock,
  activity: Icons.Activity,
  linechart: Icons.LineChart,
  layoutdashboard: Icons.LayoutDashboard,
  folder: Icons.Folder,
  folderopen: Icons.FolderOpen,
  logout: Icons.LogOut,
  arrowupdown: Icons.ArrowUpDown,
  gripvertical: Icons.GripVertical,
  vault: Icons.Vault,
  inbox: Icons.Inbox,
  mail: Icons.Mail,
  mailopen: Icons.MailOpen,
  sprout: Icons.Sprout,
  slidershorizontal: Icons.SlidersHorizontal,
  helpcircle: Icons.HelpCircle,
};

export default function LucideIcon({ name, className = '', size }: LucideIconProps) {
  const normalizedKey = (name || '').toLowerCase().replace(/[-_]/g, '');
  const IconComponent = iconMap[normalizedKey] || Icons.HelpCircle;
  return <IconComponent className={className} size={size} />;
}

export type { LucideIconProps };
